/**
 * Must stay in sync with root `vercel.json` `crons` array (paths + schedules).
 * Used by `/api/admin/health` for the cron status table row list.
 */
export const VERCEL_CRON_DEFINITIONS = [
  { path: '/api/cron/check-stuck-payments', schedule: '*/30 * * * *' },
  { path: '/api/cron/cleanup-expired-sessions', schedule: '0 1 * * *' },
  { path: '/api/cron/cleanup-pending-signups', schedule: '0 3 * * *' },
  { path: '/api/cron/expire-credits', schedule: '0 1 * * *' },
  { path: '/api/cron/parent-pack-billing', schedule: '1 0 1 * *' },
  { path: '/api/cron/parent-absence-alerts', schedule: '0 19 * * *' },
  { path: '/api/cron/parent-balance-alerts', schedule: '0 8 * * *' },
  { path: '/api/cron/pack-request-check', schedule: '0 7 * * *' },
  { path: '/api/cron/ceo-briefing', schedule: '15 7 * * *' },
  { path: '/api/cron/commission-t2-check', schedule: '0 9 * * *' },
  { path: '/api/cron/loyalty-bonus-check', schedule: '0 9 * * *' },
  { path: '/api/cron/process-renewals', schedule: '0 7 * * *' },
  { path: '/api/cron/detect-churn', schedule: '0 2 * * *' },
  { path: '/api/cron/daily-summary', schedule: '55 5 * * *' },
  { path: '/api/cron/compute-benchmarks', schedule: '0 1 * * *' },
  { path: '/api/cron/recompute-health-scores', schedule: '0 2 * * *' },
  { path: '/api/cron/status-ping', schedule: '*/5 * * * *' },
  { path: '/api/cron/snapshot-mrr', schedule: '0 22 * * *' },
  { path: '/api/cron/check-token-health', schedule: '0 8 * * 1' },
  { path: '/api/cron/renewal-reminders', schedule: '0 7 * * *' },
  { path: '/api/cron/weekly-backup', schedule: '0 3 * * 0' },
  { path: '/api/cron/monthly-backup', schedule: '0 2 1 * *' },
  { path: '/api/cron/cleanup-status-checks', schedule: '0 1 * * 1' },
  { path: '/api/cron/referral-automation', schedule: '0 3 2 * *' },
  { path: '/api/cron/onboarding-stall', schedule: '0 */6 * * *' },
  { path: '/api/cron/upgrade-nudge', schedule: '0 6 * * *' },
  { path: '/api/cron/weekly-owner-report', schedule: '0 6 * * 0' },
  { path: '/api/cron/watchdog', schedule: '0 * * * *' },
  { path: '/api/cron/payment-alert', schedule: '0 */2 * * *' },
  { path: '/api/cron/payment-retry', schedule: '0 7 * * *' },
  { path: '/api/cron/abandon-stale-carts', schedule: '0 4 * * *' },
  { path: '/api/cron/sync-bosta-card-orders', schedule: '*/15 * * * *' },
  { path: '/api/cron/process-outbox', schedule: '*/2 * * * *' },
  { path: '/api/cron/sync-wa-templates', schedule: '15 * * * *' },
  { path: '/api/cron/class-reminders', schedule: '0 5 * * *' },
] as const;
