-- ============================================================================
-- generate-baseline.sql — emits the AS-IS baseline DDL for the public schema
-- ----------------------------------------------------------------------------
-- Run this against LIVE (read-only) to produce the text of
--   supabase/migrations/00000000000000_baseline.sql
-- It returns ordered rows (sort_key, ddl). Concatenate ddl with newlines in
-- sort_key order to get the baseline file. NOTHING here mutates the database.
--
-- Faithfulness rules:
--   * Captures the public schema EXACTLY as it exists, excluding objects owned
--     by extensions (pg_depend deptype 'e') — those come back via CREATE
--     EXTENSION. Over-permissioned / mis-calibrated objects are captured as-is;
--     they are corrected in later phases, never here.
--   * Dependency-safe order: extensions -> tables(columns) -> functions ->
--     PK/UNIQUE/CHECK -> FK -> indexes -> triggers -> RLS enable -> policies ->
--     views -> grants -> storage policies. `check_function_bodies = off` makes
--     the order robust for SQL-bodied functions that reference later objects.
-- ============================================================================
WITH
pub AS (SELECT oid FROM pg_namespace WHERE nspname = 'public'),
pubrel AS (
  SELECT c.oid, c.relname, c.relkind, c.relrowsecurity, c.relforcerowsecurity, c.reloptions
  FROM pg_class c
  WHERE c.relnamespace = (SELECT oid FROM pub)
    AND c.relkind IN ('r','v','m','p')
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'e')
),
pubtab AS (SELECT * FROM pubrel WHERE relkind IN ('r','p')),
pubproc AS (
  SELECT p.oid, p.proname
  FROM pg_proc p
  WHERE p.pronamespace = (SELECT oid FROM pub)
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')
),
ddl AS (
  ----------------------------------------------------------------------------
  -- 00 — file header + safety SETs
  ----------------------------------------------------------------------------
  SELECT '00_000'::text AS sk, E'-- ============================================================================\n'
      || E'-- 00000000000000_baseline.sql\n'
      || E'-- AS-IS photograph of the live production public schema. Generated by\n'
      || E'-- scripts/schema/generate-baseline.sql. Do NOT hand-edit; regenerate.\n'
      || E'-- Captures objects exactly as they exist in prod (including ones that are\n'
      || E'-- corrected in later phases). Applying this to a fresh DB reproduces live.\n'
      || E'-- ============================================================================\n'
      || E'SET statement_timeout = 0;\n'
      || E'SET lock_timeout = 0;\n'
      || E'SET client_min_messages = warning;\n'
      || E'SET check_function_bodies = off;\n'
      || E'SET row_security = off;\n'
      || E'SET search_path = public, extensions;\n' AS ddl

  ----------------------------------------------------------------------------
  -- 01 — extensions. Managed (Supabase-only) ones are guarded so the baseline
  --      also applies on a plain Postgres (CI/local); on Supabase they install.
  ----------------------------------------------------------------------------
  UNION ALL
  SELECT '01_000', E'\n-- ---------- extensions ----------'
  UNION ALL
  SELECT '01_' || lpad((row_number() over (order by e.extname))::text,3,'0'),
    CASE
      WHEN e.extname IN ('pg_net','pg_cron','supabase_vault','pg_graphql','pgsodium','pgjwt') THEN
        format($f$DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = %L) THEN CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I; END IF; END $$;$f$,
               e.extname, e.extname, n.nspname)
      ELSE
        format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname)
    END
  FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
  WHERE e.extname <> 'plpgsql'  -- always present

  ----------------------------------------------------------------------------
  -- 10 — tables (columns + NOT NULL + DEFAULT only; constraints added later)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '10_000', E'\n-- ---------- tables ----------'
  UNION ALL
  SELECT '10_' || t.relname,
    format('CREATE TABLE public.%I (', t.relname) || E'\n  '
    || (SELECT string_agg(
            format('%I %s', a.attname, format_type(a.atttypid, a.atttypmod))
            || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
            || CASE WHEN ad.adbin IS NOT NULL
                    THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                    ELSE '' END,
            E',\n  ' ORDER BY a.attnum)
        FROM pg_attribute a
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE a.attrelid = t.oid AND a.attnum > 0 AND NOT a.attisdropped)
    || E'\n);'
  FROM pubtab t

  ----------------------------------------------------------------------------
  -- 20 — functions (verbatim definitions). Created before constraints/policies
  --      so anything referencing them resolves.
  ----------------------------------------------------------------------------
  UNION ALL SELECT '20_000', E'\n-- ---------- functions ----------'
  UNION ALL
  SELECT '20_' || p.proname || '_' || substr(md5(pg_get_function_identity_arguments(p.oid)),1,8),
         pg_get_functiondef(p.oid) || ';'
  FROM pubproc p

  ----------------------------------------------------------------------------
  -- 30 — primary keys, then unique, then check (FKs deferred to 31)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '30_000', E'\n-- ---------- primary / unique / check constraints ----------'
  UNION ALL
  SELECT '30_' || CASE c.contype WHEN 'p' THEN '1' WHEN 'u' THEN '2' ELSE '3' END
         || '_' || t.relname || '_' || c.conname,
         format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', t.relname, c.conname, pg_get_constraintdef(c.oid))
  FROM pg_constraint c JOIN pubtab t ON t.oid = c.conrelid
  WHERE c.contype IN ('p','u','c')

  ----------------------------------------------------------------------------
  -- 31 — foreign keys (after all tables + PKs exist)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '31_000', E'\n-- ---------- foreign keys ----------'
  UNION ALL
  SELECT '31_' || t.relname || '_' || c.conname,
         format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', t.relname, c.conname, pg_get_constraintdef(c.oid))
  FROM pg_constraint c JOIN pubtab t ON t.oid = c.conrelid
  WHERE c.contype = 'f'

  ----------------------------------------------------------------------------
  -- 40 — indexes (those not already created by a constraint)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '40_000', E'\n-- ---------- indexes ----------'
  UNION ALL
  SELECT '40_' || t.relname || '_' || ic.relname,
         pg_get_indexdef(i.indexrelid) || ';'
  FROM pg_index i
  JOIN pubtab t ON t.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid AND c.contype IN ('p','u','x'))

  ----------------------------------------------------------------------------
  -- 50 — triggers
  ----------------------------------------------------------------------------
  UNION ALL SELECT '50_000', E'\n-- ---------- triggers ----------'
  UNION ALL
  SELECT '50_' || t.relname || '_' || tg.tgname,
         pg_get_triggerdef(tg.oid) || ';'
  FROM pg_trigger tg JOIN pubtab t ON t.oid = tg.tgrelid
  WHERE NOT tg.tgisinternal

  ----------------------------------------------------------------------------
  -- 60 — enable RLS (+ FORCE where set)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '60_000', E'\n-- ---------- row level security ----------'
  UNION ALL
  SELECT '60_' || t.relname,
         format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t.relname)
         || CASE WHEN t.relforcerowsecurity
                 THEN format(E'\nALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', t.relname)
                 ELSE '' END
  FROM pubtab t WHERE t.relrowsecurity

  ----------------------------------------------------------------------------
  -- 70 — RLS policies (reconstructed from pg_policy; created after functions)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '70_000', E'\n-- ---------- policies ----------'
  UNION ALL
  SELECT '70_' || t.relname || '_' || pol.polname,
         format('CREATE POLICY %I ON public.%I', pol.polname, t.relname)
         || ' AS ' || CASE WHEN pol.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END
         || ' FOR ' || CASE pol.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT'
                                       WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE' ELSE 'ALL' END
         || ' TO ' || (
              SELECT string_agg(CASE WHEN r = 0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(r)) END, ', ' ORDER BY r)
              FROM unnest(pol.polroles) AS r)
         || COALESCE(' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '')
         || COALESCE(' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '')
         || ';'
  FROM pg_policy pol JOIN pubtab t ON t.oid = pol.polrelid

  ----------------------------------------------------------------------------
  -- 80 — views (with reloptions e.g. security_invoker)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '80_000', E'\n-- ---------- views ----------'
  UNION ALL
  SELECT '80_' || v.relname,
         format('CREATE OR REPLACE VIEW public.%I', v.relname)
         || COALESCE(' WITH (' || array_to_string(v.reloptions, ', ') || ')', '')
         || ' AS ' || E'\n' || pg_get_viewdef(v.oid, true)
  FROM pubrel v WHERE v.relkind = 'v'

  ----------------------------------------------------------------------------
  -- 90 — table grants (frozen as-is for anon/authenticated/service_role/PUBLIC)
  ----------------------------------------------------------------------------
  UNION ALL SELECT '90_000', E'\n-- ---------- table grants (frozen as-is) ----------'
  UNION ALL
  SELECT '90_' || t.relname || '_' || g.grantee,
         'GRANT ' || string_agg(g.priv, ', ' ORDER BY g.priv)
         || format(' ON public.%I TO %s;', t.relname,
                   CASE WHEN g.grantee = 'PUBLIC' THEN 'PUBLIC' ELSE quote_ident(g.grantee) END)
  FROM pubrel t   -- tables, partitioned tables AND views (views carry grants too)
  CROSS JOIN LATERAL (
    SELECT CASE WHEN ae.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(ae.grantee) END AS grantee,
           ae.privilege_type AS priv
    FROM pg_class t_acl
    CROSS JOIN aclexplode(COALESCE(t_acl.relacl, acldefault('r', t_acl.relowner))) ae
    WHERE t_acl.oid = t.oid
  ) g
  WHERE t.relkind IN ('r','p','v')
    AND g.grantee IN ('anon','authenticated','service_role','PUBLIC')
  GROUP BY t.relname, g.grantee

  ----------------------------------------------------------------------------
  -- 94 — revoke the DEFAULT public EXECUTE from every function. Postgres grants
  --      EXECUTE to PUBLIC on creation; prod has revoked it on the locked-down
  --      RPCs (e.g. ai_execute_query). Revoking here, then re-granting PUBLIC in
  --      95 only where prod still has it, reproduces the exact ACL as-is.
  ----------------------------------------------------------------------------
  UNION ALL SELECT '94_000', E'\n-- ---------- revoke default public EXECUTE (reproduce lockdowns) ----------'
  UNION ALL
  SELECT '94_' || p.proname || '_' || substr(md5(pg_get_function_identity_arguments(p.oid)),1,8),
         format('REVOKE EXECUTE ON FUNCTION public.%I(%s) FROM PUBLIC;',
                p.proname, pg_get_function_identity_arguments(p.oid))
  FROM pubproc p

  ----------------------------------------------------------------------------
  -- 95 — routine (EXECUTE) grants frozen as-is
  ----------------------------------------------------------------------------
  UNION ALL SELECT '95_000', E'\n-- ---------- function grants (frozen as-is) ----------'
  UNION ALL
  SELECT '95_' || p.proname || '_' || substr(md5(pg_get_function_identity_arguments(p.oid)),1,8) || '_' || g.grantee,
         format('GRANT EXECUTE ON FUNCTION public.%I(%s) TO %s;',
                p.proname, pg_get_function_identity_arguments(p.oid),
                CASE WHEN g.grantee = 'PUBLIC' THEN 'PUBLIC' ELSE quote_ident(g.grantee) END)
  FROM pubproc p
  CROSS JOIN LATERAL (
    SELECT DISTINCT CASE WHEN ae.grantee = 0 THEN 'PUBLIC' ELSE pg_get_userbyid(ae.grantee) END AS grantee
    FROM pg_proc pp
    CROSS JOIN aclexplode(COALESCE(pp.proacl, acldefault('f', pp.proowner))) ae
    WHERE pp.oid = p.oid AND ae.privilege_type = 'EXECUTE'
  ) g
  WHERE g.grantee IN ('anon','authenticated','service_role','PUBLIC')

  ----------------------------------------------------------------------------
  -- A0 — storage.objects policies (guarded: only if storage.objects exists)
  ----------------------------------------------------------------------------
  UNION ALL SELECT 'a0_000', E'\n-- ---------- storage.objects policies (guarded) ----------'
  UNION ALL
  SELECT 'a0_' || pol.policyname,
    format($f$DO $$ BEGIN IF to_regclass('storage.objects') IS NOT NULL THEN EXECUTE %L; END IF; END $$;$f$,
      format('CREATE POLICY %I ON storage.objects', pol.policyname)
      || ' AS ' || CASE WHEN pol.permissive = 'PERMISSIVE' THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END
      || ' FOR ' || pol.cmd
      || ' TO ' || array_to_string(pol.roles, ', ')
      || COALESCE(' USING (' || pol.qual || ')', '')
      || COALESCE(' WITH CHECK (' || pol.with_check || ')', ''))
  FROM pg_policies pol WHERE pol.schemaname = 'storage'
)
SELECT sk, ddl FROM ddl ORDER BY sk;
