-- ============================================================================
-- Follow-up to 20260804120000 — actually close the EXECUTE surface on
-- public.sessions_derive_center_id().
--
-- ****************************************************************************
-- * NOT APPLIED — Eyad applies this by hand.                                 *
-- * CLAUDE.md rule 5: migrations are a manual apply to production. Merging   *
-- * this file does NOT apply it (tested 15 July 2026: PR #159 merged as      *
-- * 80f82ba and the columns were still absent 8 minutes later).              *
-- ****************************************************************************
--
-- WHY THIS FILE EXISTS — a Claude-authored defect that reached production
-- ---------------------------------------------------------------------------
-- 20260804120000_sessions_tenant_key_and_occurrence_uniqueness.sql (applied
-- 4 August 2026, recorded in the migration history as 20260804094631) ends
-- block 1b with:
--
--     REVOKE ALL ON FUNCTION public.sessions_derive_center_id() FROM PUBLIC;
--
-- and a comment claiming it "matches the standing 'revoke anonymous EXECUTE
-- on SECURITY DEFINER helpers' rule". It does not. `REVOKE ... FROM PUBLIC`
-- removes only the implicit PUBLIC grant; it does not touch Supabase's
-- explicit default grants to `anon` and `authenticated`, which are separate
-- ACL entries. The statement ran, and the surface stayed open.
--
-- The comment was written by Claude, not by Eyad, and it asserted a property
-- the catalog does not have. This file corrects the catalog; a note added to
-- the merged file corrects the record. The already-applied SQL in that file is
-- deliberately NOT rewritten — it has run, and editing applied statements in
-- place is worse than the defect.
--
-- SEVERITY: LOW, and stated honestly rather than talked up.
--   - The function returns `trigger`. PostgREST does not expose trigger
--     functions, so there is no HTTP call path to it.
--   - Postgres refuses a direct `SELECT public.sessions_derive_center_id()`
--     with 42809 ("trigger functions can only be called as triggers"),
--     regardless of who holds EXECUTE.
--   - Revoking does not disable the trigger: Postgres checks EXECUTE at
--     CREATE TRIGGER time, not at fire time.
-- The problem is not exploitability. The problem is that the committed comment
-- and the live catalog disagree, and a reader auditing SECURITY DEFINER
-- surfaces would tick this one off as closed when it is not.
--
-- PRECONDITIONS, re-queried live 4 August 2026 immediately before writing this
-- (project lczmjpnbuhnsislcvzar, read-only):
--
--   SELECT p.proname, p.prosecdef, p.prorettype::regtype::text,
--          array_to_string(p.proacl, ' | ')
--     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--    WHERE n.nspname = 'public'
--      AND p.proname IN ('sessions_derive_center_id','spend_credits_atomic');
--
--   sessions_derive_center_id  secdef=t  returns=trigger
--     proacl = {postgres=X/postgres, anon=X/postgres,
--               authenticated=X/postgres, service_role=X/postgres}
--   spend_credits_atomic       secdef=t  returns=boolean
--     proacl = {postgres=X/postgres, service_role=X/postgres}
--
--   PUBLIC EXECUTE on sessions_derive_center_id .......... 0   (the merged
--                                                 REVOKE did do this much)
--   anon + authenticated EXECUTE ......................... 2   (this is the gap)
--   trg_sessions_derive_center_id present ................ 1
--
-- `spend_credits_atomic` is the reference shape: {postgres, service_role}.
-- After this file, sessions_derive_center_id matches it.
--
-- WHY service_role IS KEPT. It is the shape every other locked-down SECURITY
-- DEFINER helper in this schema already has (see the 20260625/20260626
-- lockdown migrations), and service_role is the platform's own trusted role,
-- not an anonymous or end-user surface. Removing it would be a different,
-- broader change and is not what this file is for.
--
-- SCHEMA SNAPSHOT: no change expected, and this is not a guess. db/schema.snapshot
-- is rebuilt from migrations on a vanilla Postgres by scripts/schema/rebuild.sh,
-- where Supabase's ALTER DEFAULT PRIVILEGES grants to anon/authenticated do not
-- exist — so the function has no anon/authenticated ACL entry to revoke there
-- and emits no ROUTINE_GRANT lines either way. Verified by rebuilding twice on a
-- throwaway Postgres 17.10 (with and without this file): the two snapshots are
-- byte-identical, and both match the committed db/schema.snapshot exactly.
--
-- The corollary is worth stating, because it is the reason the defect survived
-- review: THE DRIFT GATE CANNOT SEE THIS. check-drift.sh compares a rebuild of
-- the migrations against the committed snapshot; neither side is production.
-- Production's extra anon/authenticated grants are invisible to it. Grant drift
-- on Supabase default privileges has to be checked against the live catalog by
-- hand — CI will never fail on it.
-- ============================================================================

BEGIN;

-- Idempotent by nature: REVOKE on a privilege that is not held is a no-op, so
-- this is safe to re-run and safe on a partial apply (§5.2 of the prior file).
REVOKE ALL ON FUNCTION public.sessions_derive_center_id() FROM anon, authenticated;

COMMIT;

-- ============================================================================
-- POST-APPLY VERIFICATION — run this, do not assume (CLAUDE.md rule 2)
--
--   SELECT 'anon+authenticated EXECUTE (want 0)' AS check, count(*) AS n
--     FROM information_schema.routine_privileges
--    WHERE specific_schema = 'public'
--      AND routine_name = 'sessions_derive_center_id'
--      AND grantee IN ('anon','authenticated')
--   UNION ALL
--   SELECT 'PUBLIC EXECUTE (want 0)', count(*)
--     FROM information_schema.routine_privileges
--    WHERE specific_schema = 'public'
--      AND routine_name = 'sessions_derive_center_id'
--      AND grantee = 'PUBLIC'
--   UNION ALL
--   SELECT 'trigger still present (want 1)', count(*)
--     FROM pg_trigger WHERE tgname = 'trg_sessions_derive_center_id';
--
-- Expect 0, 0, 1.
--
-- And the shape check, which is the one that actually proves it:
--
--   SELECT array_to_string(p.proacl, ' | ')
--     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--    WHERE n.nspname = 'public' AND p.proname = 'sessions_derive_center_id';
--
-- Expect exactly:  postgres=X/postgres | service_role=X/postgres
-- i.e. identical in shape to spend_credits_atomic.
--
-- SANITY CHECK AFTER APPLYING — the trigger must still fire. EXECUTE is checked
-- at CREATE TRIGGER time, so revoking cannot break it, but confirm rather than
-- reason about it. Against a scratch centre/group, on a non-production copy or
-- with an immediate rollback:
--
--   BEGIN;
--     INSERT INTO public.sessions (group_id, kind, scheduled_at, status)
--     VALUES ('<a group_id whose student_groups.center_id IS NOT NULL>',
--             'center', now(), 'scheduled')
--     RETURNING center_id;   -- must come back non-NULL, derived by the trigger
--   ROLLBACK;
-- ============================================================================
